import type { Metadata } from 'next';
import { listPosts } from '@/db/posts';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Le blog',description:'Articles et échanges autour de la lecture biblique et du quotidien.'};
export default async function Blog(){
 let posts:Awaited<ReturnType<typeof listPosts>>=[];let unavailable=false;
 try{posts=await listPosts()}catch{unavailable=true}
 return <><section className="blog-hero"><div className="container blog-hero-inner"><div><span className="eyebrow">LE JOURNAL</span><h1>Des mots à lire.<br/><i>Des idées à partager.</i></h1><p>Écrivez un article ou lisez ceux des autres. La discussion continue dans les commentaires et les réactions.</p><a className="button primary" href="/blog/ecrire/">Écrire un article ↗</a></div><div className="blog-hero-side"><span className="blog-hero-symbol" aria-hidden="true">✳</span><p>La lecture continue<br/>dans les échanges.</p></div></div></section>
 <section className="container blog-publications" id="publications"><div className="blog-section-head"><div><span className="eyebrow">À DÉCOUVRIR</span><h2>Publications</h2></div><a className="text-link" href="/blog/ecrire/">Publier un article ↗</a></div>{unavailable?<p role="status" className="blog-empty">Les publications sont momentanément indisponibles. Revenez dans quelques instants.</p>:posts.length?<div className="blog-cards">{posts.map((p,index)=><article className="blog-card" key={p.id}><span className="blog-card-index">{String(index+1).padStart(2,'0')} / ARTICLE</span><time dateTime={p.created_at}>{new Date(p.created_at).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</time><h3><a href={'/blog/'+p.id+'/'}>{p.title}</a></h3><p>Par {p.author_name}</p><p>{p.content.slice(0,180)}{p.content.length>180?'…':''}</p><a className="blog-card-link" href={'/blog/'+p.id+'/'}>Lire et réagir <span aria-hidden="true">↗</span></a></article>)}</div>:<div className="blog-empty"><h3>Le premier article arrive bientôt.</h3><p>Vous pouvez ouvrir la discussion en publiant le vôtre.</p><a className="text-link" href="/blog/ecrire/">Écrire un article ↗</a></div>}</section>
 <section className="blog-notes"><div className="container"><span className="eyebrow">POUR COMMENCER</span><div className="blog-notes-grid"><div><span>01</span><h2>Prendre le temps de lire</h2><p>Revenir sur une phrase, regarder le contexte et laisser une question ouverte : parfois, la lecture commence ainsi.</p></div><div><span>02</span><h2>Faire de la place aux questions</h2><p>Comparer, discuter, réfléchir. Une question sincère peut ouvrir un nouveau chemin de lecture.</p></div></div></div></section></>
}
