'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
type Comment={id:number;post_id:number;parent_id:number|null;author_name:string;body:string;is_author:number;created_at:string};
type Kind='like'|'love'|'amen';
type State={counts:Partial<Record<Kind,number>>;mine:Kind|null};
const choices:{kind:Kind;icon:string;label:string}[]=[{kind:'like',icon:'👍',label:'J’aime'},{kind:'love',icon:'❤️',label:'J’adore'},{kind:'amen',icon:'🙏',label:'Amen'}];
export default function PostInteractions({postId,isAuthor}:{postId:number;isAuthor:boolean}){
 const [comments,setComments]=useState<Comment[]>([]),[reactions,setReactions]=useState<State>({counts:{},mine:null}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[replyTo,setReplyTo]=useState<Comment|null>(null);
 const formRef=useRef<HTMLFormElement>(null);
 const refresh=useCallback(async()=>{try{const r=await fetch(`/api/posts/${postId}/interactions`,{cache:'no-store'});const data=await r.json() as {comments:Comment[];reactions:State;error?:string;id?:number};if(!r.ok)throw new Error(data.error||'Chargement impossible.');setComments(data.comments);setReactions(data.reactions);setError('')}catch(e){setError(e instanceof Error?e.message:'Échanges indisponibles.')}finally{setLoading(false)}},[postId]);
 useEffect(()=>{void refresh()},[refresh]);
 async function react(kind:Kind){setBusy(true);setError('');try{const r=await fetch(`/api/posts/${postId}/interactions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reaction',kind})});const data=await r.json() as {comments:Comment[];reactions:State;error?:string;id?:number};if(!r.ok)throw new Error(data.error||'Réaction impossible.');setReactions(data.reactions)}catch(e){setError(e instanceof Error?e.message:'Réaction impossible.')}finally{setBusy(false)}}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/posts/${postId}/interactions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'comment',name,text:message,parentId:replyTo?.id??null})});const data=await r.json() as {comments:Comment[];reactions:State;error?:string;id?:number};if(!r.ok)throw new Error(data.error||'Commentaire impossible.');setComments(data.comments);setMessage('');setReplyTo(null)}catch(e){setError(e instanceof Error?e.message:'Votre commentaire n’a pas été enregistré.')}finally{setBusy(false)}}
 function startReply(comment:Comment){setReplyTo(comment);formRef.current?.scrollIntoView({behavior:'smooth',block:'center'})}
 function renderComment(comment:Comment,depth=0):React.ReactNode{
  const children=comments.filter(c=>c.parent_id===comment.id);
  return <div key={comment.id} className="comment" style={{marginLeft:`${Math.min(depth,3)*20}px`}}><div className="comment-meta"><strong>{comment.author_name}</strong>{comment.is_author===1&&<span className="author-badge">Auteur</span>}<time dateTime={comment.created_at}>{new Date(comment.created_at).toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}</time></div><p>{comment.body}</p><button type="button" onClick={()=>startReply(comment)}>Répondre ↗</button>{children.length>0&&<div className="comment-children">{children.map(c=>renderComment(c,depth+1))}</div>}</div>
 }
 const ids=new Set(comments.map(c=>c.id));const roots=comments.filter(c=>c.parent_id===null||!ids.has(c.parent_id));
 return <section className="interactions-section" id="echanges"><div className="container interactions-inner"><div className="interactions-heading"><span className="eyebrow">LA CONVERSATION CONTINUE</span><h2>Réagir & échanger</h2><p>Choisissez une réaction ou partagez ce que cette lecture vous inspire.</p></div><div className="reactions" aria-label="Réactions à l’article">{choices.map(choice=><button type="button" key={choice.kind} disabled={busy||loading} aria-pressed={reactions.mine===choice.kind} onClick={()=>void react(choice.kind)}><span aria-hidden="true">{choice.icon}</span> {choice.label} <b>{reactions.counts[choice.kind]??0}</b></button>)}</div><div className="discussion-grid"><div><h3>Commentaires <span>{comments.length}</span></h3>{loading?<p>Chargement des échanges…</p>:roots.length?roots.map(c=>renderComment(c)):<p className="empty-comments">Soyez la première personne à ouvrir la discussion.</p>}</div><form className="comment-form" ref={formRef} onSubmit={submit}><span className="eyebrow">PRENDRE LA PAROLE</span><h3>{replyTo?`Répondre à ${replyTo.author_name}`:'Laisser un commentaire'}</h3>{replyTo&&<button type="button" className="cancel-reply" onClick={()=>setReplyTo(null)}>Annuler la réponse ×</button>}{!isAuthor&&<><label htmlFor="comment-name">Votre nom affiché</label><input id="comment-name" required minLength={2} maxLength={32} value={name} onChange={e=>setName(e.target.value)} placeholder="Votre prénom ou pseudo"/></>}<label htmlFor="comment-text">Votre commentaire</label><textarea id="comment-text" required minLength={3} maxLength={1500} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Écrivez votre réponse…"/><button className="button primary" disabled={busy} type="submit">{busy?'Envoi…':'Publier le commentaire ↗'}</button><small>Votre nom et votre commentaire seront visibles par tous les lecteurs.</small></form></div>{error&&<p className="interaction-error" role="alert">{error}</p>}</div></section>
}
